### ISSUE TITLE
配置信息有误

### ISSUE THREAD

**Issue by iakirago** [Q1mi/bluebell#28]
db: bluebell_pre 应该改为  db: bluebell

**Comment by JefferyUnreachable** [comment]
佬，能留个qq嘛，请教一些配置的问题。呜呜..或者我的qq是2196095381

**Comment by JefferyUnreachable** [comment]
> db: bluebell_pre 应该改为 db: bluebell

佬，能留个qq嘛，请教一些配置的问题。呜呜..或者我的qq是2196095381

**Comment by iakirago** [comment]
> > db: bluebell_pre 应该改为 db: bluebell
> 
> 佬，能留个qq嘛，请教一些配置的问题。呜呜..或者我的qq是2196095381

什么问题

**Comment by Q1mi** [comment]
配置文件根据自己需要调整即可。
